[package]
name = "sys"
version = "0.1.0"
edition = "2021"
license = "WTFPL"
publish = false
default-run = "sys"

[features]
default = ["binance", "coinbase", "ftx", "kraken"]
binance = ["dep:binance-rs-async"]
coinbase = ["dep:coinbase-rs"]
ftx = ["dep:ftx"]
kraken = ["dep:kraken_sdk_rest"]

[dependencies]
async-recursion = "1.0.0"
async-trait = "0.1.50"
#binance-rs-async = { version = "1.2.0", features = ["wallet_api"]}
#binance-rs-async = { path = "../binance-rs-async", features = ["wallet_api"]}
binance-rs-async = { git = "https://github.com/mvines/binance-rs-async", rev = "bca0331675f39924a06c4c1fbfacc143d3774735", features = ["wallet_api"], optional = true }
bincode = "1.3"
chrono = "0.4"
chrono-humanize = "0.2.1"
clap = "2.33"
#coinbase-rs = { path = "../coinbase-rs" }
coinbase-rs = { git = "https://github.com/mvines/coinbase-rs.git", rev = "0ada57aff324e4955db772caebd0e46190333a8c", optional = true }
console = "0.14.1"
fd-lock = "3.0.0"
ftx = { git = "https://github.com/fabianboesiger/ftx", rev = "bb98235d356dd1a2becc5bdf32a4b738311ed434", optional = true }
#ftx = { git = "https://github.com/mvines/ftx", rev = "22dea8cf63269645eb220c9ce5ffdd0b746a9ceb" }
#ftx = { path = "../ftx" }
futures = "0.3.25"
influxdb-client = "0.1.4"
itertools = "0.10.0"
jup-ag = "0.6.0"
#jup-ag = { path = "../jup_ag" }
#kraken_sdk_rest = { path = "../kraken_sdk_rust/kraken_sdk_rest" }
kraken_sdk_rest = { git = "https://github.com/mvines/kraken_sdk_rust", rev = "80c634b3a8527f653db989689b298496dad30d4e", optional = true }
#kraken_sdk_rest = "0.18.0"
lazy_static = "1.4.0"
log = "0.4.17"
pickledb = { git = "https://github.com/seladb/pickledb-rs.git", rev = "0.5.0" }
#pickledb = { path = "../pickledb-rs" }
reqwest = "0.11"
rust_decimal = "1.23"
rust_decimal_macros = "1.23"
separator = "0.4.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
simple_excel_writer = "0.1.9"
solana-clap-utils = "=1.14.17"
solana-cli-config = "=1.14.17"
solana-cli-output = "=1.14.17"
solana-client = "=1.14.17"
solana-logger = "=1.14.17"
solana-remote-wallet = "=1.14.17"
solana-sdk = "=1.14.17"
solana-transaction-status = "=1.14.17"
solana-vote-program = "=1.14.17"            # Remove `solana-vote-program` dependency upon update to Solana 1.16
spl-associated-token-account = "1.0.3"
spl-token = "3.2.0"
spl-token-lending = { git = "https://github.com/solana-labs/solana-program-library.git", rev = "1d1c2b178b8cf2ed3e28006c27b2ba5b3d039d67" }
strum = { version = "0.23", features = ["derive"] }
thiserror = "1.0"
tokio = { version = "1", features = ["macros", "time"] }
tulipv2-sdk-common = "0.9.5"

